chatbot_responses = {
    "hello": "Hi there! How can I assist you today?",
    "hi": "Hello! What can I help you with today?",
    "hey": "Hey there! How can I help you today?",
    "no worries": "Hey there! How can I help you today?",
    "what's up": "Hey there! How can I help you today?",
    "company": "We're a Saas company. Want to learn more about our services?",
    "help": "I'm here to help! Could you describe the issue you're facing?",
    "issue": "I’m sorry to hear that! Can you provide more details about the problem so I can assist you?",
    "prices": "Our pricing is according to market standards. Would you like a detailed breakdown?",
    "cost": "You can view our pricing details at our website. Need help deciding which plan is best for you?",
    "open": "We're open from 9-10. Feel free to reach out during those times!",
    "hours": "Our business hours are 9-10. Need anything else?",
    "faq": "We are building it. Let me know if you need further clarification.",
    "contact": "You can reach us at dvpp162163@gmail.com or call us at 9735982211. Would you like to contact us now?",
    "email": "Feel free to contact us via dvpp162163@gmail.com or call us at 9735982211. Need help with anything else?",
    "hire": "Yes you can definitely hire me",
    "order": "You can track your order at main website. Need further assistance?",
    "service": "To book a service, use google, or I can help guide you through the process!",
    "located": "We're located at India. Would you like directions?",
    "address": "You can visit us at India. Want to know how to get here?",
    "account": "You can create an account simply by google. Need help with anything else?",
    "log in": "To log in, use google or reset your password if needed.",
    "bye": "You're welcome! Have a great day!",
    "thank": "Thanks for reaching out! If you need anything else, feel free to ask."
}